### ISSUE TITLE
Enhancement: Add Collapse all button and Form type

### ISSUE THREAD

**Issue by daggen** [MscrmTools/MsCrmTools.FormRelated#3]
Great plugin!
Two possible enhancements.
1) On left list view add a link label for collapsing all root nodes and folders. This will greatly help now with CRM 2016 stuff which occupy most of the list today. See Web Resource manager for reference

2) On right list view add a new column for form type. This will help to distinguish between forms which have same name but different types.

Thanks for the great tool and keep ut the great work!

**Comment by MscrmTools** [comment]
Thank you for this feedback, implementation is in progress
